package com.zw.miaofuspd.mapper;

import com.zw.pojo.AppMessage ;

import java.util.List;

public interface AppMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    int insert(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    AppMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    List<AppMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    int updateByPrimaryKey(AppMessage record);
    /**
     *
     * 添加 （匹配有值的字段）
     * @param record 保存对象
     * @return 影响行数
     **/
    int insertSelective(AppMessage record);

}