package com.zw.miaofuspd.mapper;

import com.zw.pojo.BusinessRepayment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessRepaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_repayment
     *
     * @mbggenerated Fri Jul 20 14:24:23 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_repayment
     *
     * @mbggenerated Fri Jul 20 14:24:23 CST 2018
     */
    int insert(BusinessRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_repayment
     *
     * @mbggenerated Fri Jul 20 14:24:23 CST 2018
     */
    BusinessRepayment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_repayment
     *
     * @mbggenerated Fri Jul 20 14:24:23 CST 2018
     */
    List<BusinessRepayment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_repayment
     *
     * @mbggenerated Fri Jul 20 14:24:23 CST 2018
     */
    int updateByPrimaryKey(BusinessRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_repayment
     *
     * @mbggenerated Fri Jul 20 14:24:23 CST 2018
     */
    int updateRepaymentById(BusinessRepayment record);

    /**
     * 获取某个订单某期的还款计划
     * @param record
     *              orderId 订单id
     *              period 期数
     * @return 返回还款计划信息
     */
    BusinessRepayment getByOrderIdAndPeriod(BusinessRepayment record);

    /**
     * 更新某个订单某期的还款计划
     * @param record
     *              orderId 订单id
     *              period 期数
     * @return 影响行数
     */
    int updateByOrderIdAndPeriod(@Param("record") BusinessRepayment record);

    /**
     * 根据订单id获取当前期数信息
     * @param record
     * @return
     */
    List<BusinessRepayment> findListByOrderId(@Param("record") BusinessRepayment record);
    /**
     * 根据还款状态获取还款信息
     * @param status 还款状态
     * @return 还款信息
     */
    List<BusinessRepayment> findRepaymentInfoByStatus(@Param("status") String status);

}