package com.zw.miaofuspd.mapper;

import com.zw.pojo.OrderOperationRecord;

import java.util.List;

public interface OrderOperationRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_record
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_record
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    int insert(OrderOperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_record
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    OrderOperationRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_record
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    List<OrderOperationRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_record
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    int updateByPrimaryKey(OrderOperationRecord record);


    int insertOrderOperRecord(OrderOperationRecord record);
}