package com.zw.miaofuspd.mapper;


import com.zw.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    int updateByPrimaryKey(Order record);


    /**
     * 按订单编号更新订单信息
     * @author 陈淸玉 create on 2018-07-19
     * @param order 订单实体
     * @return 影响行数
     */
    int updateOrderByNo(Order order);

    /**
     * 按订单编号获取订单编号信息
     * @author 陈淸玉 create on 2018-07-19
     * @param orderNo 订单Id
     * @return 一条订单数据
     */
    Order getOrderInfoByNo(@Param("orderNo") String orderNo);

    }