package com.zw.miaofuspd.mapper;

import com.zw.miaofuspd.facade.pojo.Customer ;

import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_customer
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_customer
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_customer
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_customer
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_customer
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    int updateByPrimaryKey(Customer record);

    int  updateByPrimaryKeySelective(Customer record);
}