/**
 * Created by Administrator on 2017/3/15 0015.
 */
Ext.define('MyApp.view.MiddleSave',{
    extend:'Ext.Container',
    xtype:'middleSaveview',
    requires:[
        'Ext.field.Hidden'
    ],
    config: {
        zIndex:-10,
        id: 'middleSaveview',
        style:'background:#F2F2F2',
        items:[
            {
                xtype:"hiddenfield",
                id:'salesmanId',//办单员id
                value:""
            },
            {
                xtype:"hiddenfield",
                id:'merchanId',//商户ID
                value:""
            },
            {
                xtype:"hiddenfield",
                id:'typeName',//商品类型名称
                value:""
            },
            {
                xtype:'hiddenfield',
                id:'typeId'//商品类型id
            },
            {
                xtype:'hiddenfield',
                id:'brand_Name'//品牌名称
            },
            {
                xtype:'hiddenfield',
                id:'model_Name'//型号名称
            },
            {
                xtype:'hiddenfield',
                id:'edition_Name'//版本名称名称
            },
            {
                xtype:'hiddenfield',
                id:'codeProductId'//生成二维码产品id
            },
            {
                xtype:'hiddenfield',
                id:'order_id'
            },
            // appHost
            {
                xtype:'hiddenfield',
                id:'appHost'
            },
            // credit_pre_amount
            {
                xtype:'hiddenfield',
                id:'credit_pre_amount'
            },
            //产品id
            {
                xtype:'hiddenfield',
                id:'product_id',
                name:'product_id'
            },
            {
                xtype:'hiddenfield',
                id:'dueDate',
                name:'dueDate'
            },
            {
                xtype:'hiddenfield',
                id:'getHost',
                name:'getHost'
            },
            {
                xtype:'hiddenfield',
                id:'getRootPath',
                name:'getRootPath'
            },
            {
                xtype:'hiddenfield',
                id:'headImgSrc',
                name:'headImgSrc'
            },
            {
                xtype:'hiddenfield',
                id:'referenceId'//用于分享
            },
            //存客户id
            {
                xtype:'hiddenfield',
                id:'customerId',
                name:'customerId'
            },
            //客户姓名
            {
                xtype:'hiddenfield',
                id:'customerName',
                name:'customerName'
            },
            //存客户身份证号码
            {
              xtype:'hiddenfield',
              id:'customerCardNum',
              name:'customerCardNum'
            },
            //存客户电话
            {
                xtype:'hiddenfield',
                id:'customerTel',
                name:'customerTel'
            }
        ],
        listeners:{
            show:function(){
            }
        }
    },
    initialize:function(){
       MiddleviewThis=this;
    }
});