package com.zw.erp.ws.crmorderservice.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-12-15T09:40:23.670+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://crm.service.apt.com/", name = "ICrmOrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICrmOrderService {

    @WebMethod
    @RequestWrapper(localName = "getCrmPaycontrolsByAcc", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmPaycontrolsByAcc")
    @ResponseWrapper(localName = "getCrmPaycontrolsByAccResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmPaycontrolsByAccResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmPaycontrolsByAcc(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "searchRansomFloor", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SearchRansomFloor")
    @ResponseWrapper(localName = "searchRansomFloorResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SearchRansomFloorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String searchRansomFloor(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "rejectApply", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.RejectApply")
    @ResponseWrapper(localName = "rejectApplyResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.RejectApplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String rejectApply(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getSettCrmOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetSettCrmOrders")
    @ResponseWrapper(localName = "getSettCrmOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetSettCrmOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getSettCrmOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "saveFullScaleContractInfo", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveFullScaleContractInfo")
    @ResponseWrapper(localName = "saveFullScaleContractInfoResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveFullScaleContractInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveFullScaleContractInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "searchFloorProductDetail", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SearchFloorProductDetail")
    @ResponseWrapper(localName = "searchFloorProductDetailResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SearchFloorProductDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String searchFloorProductDetail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCrmOrdersJson", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmOrdersJson")
    @ResponseWrapper(localName = "getCrmOrdersJsonResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmOrdersJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmOrdersJson(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getCustTransferRecoderByType", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCustTransferRecoderByType")
    @ResponseWrapper(localName = "getCustTransferRecoderByTypeResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCustTransferRecoderByTypeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCustTransferRecoderByType(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "confirmAccount", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ConfirmAccount")
    @ResponseWrapper(localName = "confirmAccountResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ConfirmAccountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String confirmAccount(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getWithdrawCustomer", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetWithdrawCustomer")
    @ResponseWrapper(localName = "getWithdrawCustomerResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetWithdrawCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getWithdrawCustomer(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getCrmOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmOrders")
    @ResponseWrapper(localName = "getCrmOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getCustBankCardInfo", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCustBankCardInfo")
    @ResponseWrapper(localName = "getCustBankCardInfoResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCustBankCardInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCustBankCardInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getTransferRecord", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetTransferRecord")
    @ResponseWrapper(localName = "getTransferRecordResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetTransferRecordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getTransferRecord(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "payMoney", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PayMoney")
    @ResponseWrapper(localName = "payMoneyResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PayMoneyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String payMoney(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getDeleteCrmOrderList", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetDeleteCrmOrderList")
    @ResponseWrapper(localName = "getDeleteCrmOrderListResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetDeleteCrmOrderListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getDeleteCrmOrderList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getNeedPayCustomerList", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetNeedPayCustomerList")
    @ResponseWrapper(localName = "getNeedPayCustomerListResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetNeedPayCustomerListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getNeedPayCustomerList(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getAccountRepayDetail", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetAccountRepayDetail")
    @ResponseWrapper(localName = "getAccountRepayDetailResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetAccountRepayDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAccountRepayDetail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getOverdueOrder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetOverdueOrder")
    @ResponseWrapper(localName = "getOverdueOrderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetOverdueOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getOverdueOrder();

    @WebMethod
    @RequestWrapper(localName = "restartCrmorder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.RestartCrmorder")
    @ResponseWrapper(localName = "restartCrmorderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.RestartCrmorderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String restartCrmorder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "floorBocPaycontrolReturn", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.FloorBocPaycontrolReturn")
    @ResponseWrapper(localName = "floorBocPaycontrolReturnResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.FloorBocPaycontrolReturnResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String floorBocPaycontrolReturn(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCreditIcConfirms", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCreditIcConfirms")
    @ResponseWrapper(localName = "getCreditIcConfirmsResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCreditIcConfirmsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCreditIcConfirms(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "settleFloorOrder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SettleFloorOrder")
    @ResponseWrapper(localName = "settleFloorOrderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SettleFloorOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String settleFloorOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCrmOrderIdByApplyId", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmOrderIdByApplyId")
    @ResponseWrapper(localName = "getCrmOrderIdByApplyIdResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmOrderIdByApplyIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmOrderIdByApplyId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "setPropertiesCrmorder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SetPropertiesCrmorder")
    @ResponseWrapper(localName = "setPropertiesCrmorderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SetPropertiesCrmorderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String setPropertiesCrmorder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getWithdrawRecordList", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetWithdrawRecordList")
    @ResponseWrapper(localName = "getWithdrawRecordListResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetWithdrawRecordListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getWithdrawRecordList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getCrmApplyRecoderJson", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmApplyRecoderJson")
    @ResponseWrapper(localName = "getCrmApplyRecoderJsonResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmApplyRecoderJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmApplyRecoderJson(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getCrmpaycontrolsListByCrmOrderId", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmpaycontrolsListByCrmOrderId")
    @ResponseWrapper(localName = "getCrmpaycontrolsListByCrmOrderIdResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmpaycontrolsListByCrmOrderIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmpaycontrolsListByCrmOrderId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "saveMatchOrder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveMatchOrder")
    @ResponseWrapper(localName = "saveMatchOrderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveMatchOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveMatchOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "exportV3Info", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ExportV3Info")
    @ResponseWrapper(localName = "exportV3InfoResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ExportV3InfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String exportV3Info(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "saveClearProveFtpUrl", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveClearProveFtpUrl")
    @ResponseWrapper(localName = "saveClearProveFtpUrlResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveClearProveFtpUrlResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveClearProveFtpUrl(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getRansomFloorOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetRansomFloorOrders")
    @ResponseWrapper(localName = "getRansomFloorOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetRansomFloorOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getRansomFloorOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "payMoneyV2", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PayMoneyV2")
    @ResponseWrapper(localName = "payMoneyV2Response", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PayMoneyV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public String payMoneyV2(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getWithdrawRecord", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetWithdrawRecord")
    @ResponseWrapper(localName = "getWithdrawRecordResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetWithdrawRecordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getWithdrawRecord(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "updateCrmpaycontrol", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.UpdateCrmpaycontrol")
    @ResponseWrapper(localName = "updateCrmpaycontrolResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.UpdateCrmpaycontrolResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String updateCrmpaycontrol(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "saveTransferRecoders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveTransferRecoders")
    @ResponseWrapper(localName = "saveTransferRecodersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveTransferRecodersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveTransferRecoders(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "importCustomer", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportCustomer")
    @ResponseWrapper(localName = "importCustomerResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String importCustomer(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "payMoneyV1", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PayMoneyV1")
    @ResponseWrapper(localName = "payMoneyV1Response", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PayMoneyV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public String payMoneyV1(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getNotSettCrmOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetNotSettCrmOrders")
    @ResponseWrapper(localName = "getNotSettCrmOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetNotSettCrmOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getNotSettCrmOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "importClearOver", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportClearOver")
    @ResponseWrapper(localName = "importClearOverResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportClearOverResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String importClearOver(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getAllRepayingOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetAllRepayingOrders")
    @ResponseWrapper(localName = "getAllRepayingOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetAllRepayingOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAllRepayingOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "importOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportOrders")
    @ResponseWrapper(localName = "importOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String importOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "importClearCpc", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportClearCpc")
    @ResponseWrapper(localName = "importClearCpcResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ImportClearCpcResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String importClearCpc(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetOrderByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getOrderById(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getNotSettOrderList", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetNotSettOrderList")
    @ResponseWrapper(localName = "getNotSettOrderListResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetNotSettOrderListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getNotSettOrderList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAccountDetailList", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetAccountDetailList")
    @ResponseWrapper(localName = "getAccountDetailListResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetAccountDetailListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAccountDetailList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPayInfo", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetPayInfo")
    @ResponseWrapper(localName = "getPayInfoResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetPayInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getPayInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "printClearProve", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PrintClearProve")
    @ResponseWrapper(localName = "printClearProveResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.PrintClearProveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String printClearProve(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getExcelOrderSettlement", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetExcelOrderSettlement")
    @ResponseWrapper(localName = "getExcelOrderSettlementResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetExcelOrderSettlementResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getExcelOrderSettlement();

    @WebMethod
    @RequestWrapper(localName = "getCrmRepayRecords", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmRepayRecords")
    @ResponseWrapper(localName = "getCrmRepayRecordsResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmRepayRecordsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmRepayRecords(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "exportCrmpaycontrols", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ExportCrmpaycontrols")
    @ResponseWrapper(localName = "exportCrmpaycontrolsResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ExportCrmpaycontrolsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String exportCrmpaycontrols(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "isClearOrder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.IsClearOrder")
    @ResponseWrapper(localName = "isClearOrderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.IsClearOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String isClearOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "updateWithdrawRecord", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.UpdateWithdrawRecord")
    @ResponseWrapper(localName = "updateWithdrawRecordResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.UpdateWithdrawRecordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String updateWithdrawRecord(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getOrdersById", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetOrdersById")
    @ResponseWrapper(localName = "getOrdersByIdResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetOrdersByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getOrdersById(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "doDeleteCrmorder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.DoDeleteCrmorder")
    @ResponseWrapper(localName = "doDeleteCrmorderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.DoDeleteCrmorderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String doDeleteCrmorder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getcrmApplays", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetcrmApplays")
    @ResponseWrapper(localName = "getcrmApplaysResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetcrmApplaysResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getcrmApplays(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "transferEfBoc", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.TransferEfBoc")
    @ResponseWrapper(localName = "transferEfBocResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.TransferEfBocResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String transferEfBoc(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "executeFullScale", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ExecuteFullScale")
    @ResponseWrapper(localName = "executeFullScaleResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ExecuteFullScaleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String executeFullScale(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateZzlcfContract", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GenerateZzlcfContract")
    @ResponseWrapper(localName = "generateZzlcfContractResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GenerateZzlcfContractResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String generateZzlcfContract(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "resetWithdrawstatus", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ResetWithdrawstatus")
    @ResponseWrapper(localName = "resetWithdrawstatusResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.ResetWithdrawstatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String resetWithdrawstatus(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "saveAdvanceClearApplyInfo", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveAdvanceClearApplyInfo")
    @ResponseWrapper(localName = "saveAdvanceClearApplyInfoResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveAdvanceClearApplyInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveAdvanceClearApplyInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "saveWithdrawRecord", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveWithdrawRecord")
    @ResponseWrapper(localName = "saveWithdrawRecordResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.SaveWithdrawRecordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveWithdrawRecord(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getRepayingOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetRepayingOrders")
    @ResponseWrapper(localName = "getRepayingOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetRepayingOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getRepayingOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getSuccCrmOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetSuccCrmOrders")
    @ResponseWrapper(localName = "getSuccCrmOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetSuccCrmOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getSuccCrmOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "fullScaleGeneratorContractInfo", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.FullScaleGeneratorContractInfo")
    @ResponseWrapper(localName = "fullScaleGeneratorContractInfoResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.FullScaleGeneratorContractInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String fullScaleGeneratorContractInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getCrmProcessOrders", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmProcessOrders")
    @ResponseWrapper(localName = "getCrmProcessOrdersResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCrmProcessOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCrmProcessOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getCustTransferRecoder", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCustTransferRecoder")
    @ResponseWrapper(localName = "getCustTransferRecoderResponse", targetNamespace = "http://crm.service.apt.com/", className = "com.zw.erp.ws.crmorderservice.proxy.GetCustTransferRecoderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getCustTransferRecoder(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );
}
