package com.zw.miaofuspd.facade.pojo;

import java.math.BigDecimal;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.USER_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.PERSON_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.ACCOUNT_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.PERSON_NAME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.CONTACT_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.TEL
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.CARD_TYPE
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.CARD
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.card_register_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String cardRegisterAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.credential_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String credentialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.live_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String liveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.asset_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String assetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.profession_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String professionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.expend_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String expendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.origin
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.company
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.branch
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.manager
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.CREAT_TIME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.ALTER_TIME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String alterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.APEX1
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String apex1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.APEX2
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String apex2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.APEX3
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String apex3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.BAK
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.sale_adviser
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String saleAdviser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.occupation_type
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String occupationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.bg_cust_info_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bgCustInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.crm_cust_info_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String crmCustInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.bg_customer_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bgCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.reference_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String referenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.card_type_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String cardTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.emp_number
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String empNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.origin_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String originId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.credit_pre_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String creditPreAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.credit_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String creditAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.card_effective_time
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String cardEffectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.nation
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.birth
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.identity_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String identityComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.sex_name
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String sexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.person_face_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String personFaceState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.Fcard_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String fcardSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.Zcard_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String zcardSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.author_flag
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String authorFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.sign_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String signAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.is_identity
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String isIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.bank_error_date
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bankErrorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.bank_error_num
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bankErrorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.person_face_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String personFaceComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.link_man_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String linkManComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.person_info_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String personInfoComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.authorization_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String authorizationComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.three_code_num
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String threeCodeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.requestno
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String requestno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.sesame_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String sesameState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.phone_host_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String phoneHostState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.is_openAccount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String isOpenaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.bingcardpayno
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bingcardpayno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.red_money
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String redMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.phone_task_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String phoneTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.face_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String faceSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.call_record_url
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String callRecordUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.invitation_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String invitationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.face_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String faceStateSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.basic_complete_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String basicCompleteSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.phone_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String phoneStateSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.authorization_complete_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String authorizationCompleteSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.three_error_spdNum
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String threeErrorSpdnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.is_identity_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String isIdentitySpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.bank_errorNum_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String bankErrornumSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.taobao_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String taobaoStateSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.marital_status
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.children_status
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String childrenStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.residence_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String residenceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.Hometown_house_property
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String hometownHouseProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.Baseinfo_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String baseinfoComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.surplus_contract_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private BigDecimal surplusContractAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.sync_user_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private Integer syncUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.sync_account_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private Integer syncAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.imageinfo_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String imageinfoComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.Zcard_src_base64
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String zcardSrcBase64;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.Fcard_src_base64
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String fcardSrcBase64;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.ninetyOne_rule
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String ninetyoneRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_customer.phoneBookList
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    private String phonebooklist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.ID
     *
     * @return the value of mag_customer.ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.ID
     *
     * @param id the value for mag_customer.ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.USER_ID
     *
     * @return the value of mag_customer.USER_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.USER_ID
     *
     * @param userId the value for mag_customer.USER_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.PERSON_ID
     *
     * @return the value of mag_customer.PERSON_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.PERSON_ID
     *
     * @param personId the value for mag_customer.PERSON_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.ACCOUNT_ID
     *
     * @return the value of mag_customer.ACCOUNT_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.ACCOUNT_ID
     *
     * @param accountId the value for mag_customer.ACCOUNT_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.PERSON_NAME
     *
     * @return the value of mag_customer.PERSON_NAME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.PERSON_NAME
     *
     * @param personName the value for mag_customer.PERSON_NAME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.CONTACT_ID
     *
     * @return the value of mag_customer.CONTACT_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.CONTACT_ID
     *
     * @param contactId the value for mag_customer.CONTACT_ID
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.TEL
     *
     * @return the value of mag_customer.TEL
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.TEL
     *
     * @param tel the value for mag_customer.TEL
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.CARD_TYPE
     *
     * @return the value of mag_customer.CARD_TYPE
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.CARD_TYPE
     *
     * @param cardType the value for mag_customer.CARD_TYPE
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.CARD
     *
     * @return the value of mag_customer.CARD
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.CARD
     *
     * @param card the value for mag_customer.CARD
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.card_register_address
     *
     * @return the value of mag_customer.card_register_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCardRegisterAddress() {
        return cardRegisterAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.card_register_address
     *
     * @param cardRegisterAddress the value for mag_customer.card_register_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCardRegisterAddress(String cardRegisterAddress) {
        this.cardRegisterAddress = cardRegisterAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.credential_id
     *
     * @return the value of mag_customer.credential_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCredentialId() {
        return credentialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.credential_id
     *
     * @param credentialId the value for mag_customer.credential_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCredentialId(String credentialId) {
        this.credentialId = credentialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.live_id
     *
     * @return the value of mag_customer.live_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.live_id
     *
     * @param liveId the value for mag_customer.live_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setLiveId(String liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.asset_id
     *
     * @return the value of mag_customer.asset_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.asset_id
     *
     * @param assetId the value for mag_customer.asset_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.profession_id
     *
     * @return the value of mag_customer.profession_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.profession_id
     *
     * @param professionId the value for mag_customer.profession_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setProfessionId(String professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.expend_id
     *
     * @return the value of mag_customer.expend_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getExpendId() {
        return expendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.expend_id
     *
     * @param expendId the value for mag_customer.expend_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setExpendId(String expendId) {
        this.expendId = expendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.origin
     *
     * @return the value of mag_customer.origin
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.origin
     *
     * @param origin the value for mag_customer.origin
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.company
     *
     * @return the value of mag_customer.company
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.company
     *
     * @param company the value for mag_customer.company
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.branch
     *
     * @return the value of mag_customer.branch
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.branch
     *
     * @param branch the value for mag_customer.branch
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.manager
     *
     * @return the value of mag_customer.manager
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.manager
     *
     * @param manager the value for mag_customer.manager
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.CREAT_TIME
     *
     * @return the value of mag_customer.CREAT_TIME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.CREAT_TIME
     *
     * @param creatTime the value for mag_customer.CREAT_TIME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.ALTER_TIME
     *
     * @return the value of mag_customer.ALTER_TIME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.ALTER_TIME
     *
     * @param alterTime the value for mag_customer.ALTER_TIME
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setAlterTime(String alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.state
     *
     * @return the value of mag_customer.state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.state
     *
     * @param state the value for mag_customer.state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.APEX1
     *
     * @return the value of mag_customer.APEX1
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getApex1() {
        return apex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.APEX1
     *
     * @param apex1 the value for mag_customer.APEX1
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setApex1(String apex1) {
        this.apex1 = apex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.APEX2
     *
     * @return the value of mag_customer.APEX2
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getApex2() {
        return apex2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.APEX2
     *
     * @param apex2 the value for mag_customer.APEX2
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setApex2(String apex2) {
        this.apex2 = apex2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.APEX3
     *
     * @return the value of mag_customer.APEX3
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getApex3() {
        return apex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.APEX3
     *
     * @param apex3 the value for mag_customer.APEX3
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setApex3(String apex3) {
        this.apex3 = apex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.BAK
     *
     * @return the value of mag_customer.BAK
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBak() {
        return bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.BAK
     *
     * @param bak the value for mag_customer.BAK
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBak(String bak) {
        this.bak = bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.sale_adviser
     *
     * @return the value of mag_customer.sale_adviser
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getSaleAdviser() {
        return saleAdviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.sale_adviser
     *
     * @param saleAdviser the value for mag_customer.sale_adviser
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSaleAdviser(String saleAdviser) {
        this.saleAdviser = saleAdviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.occupation_type
     *
     * @return the value of mag_customer.occupation_type
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getOccupationType() {
        return occupationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.occupation_type
     *
     * @param occupationType the value for mag_customer.occupation_type
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setOccupationType(String occupationType) {
        this.occupationType = occupationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.bg_cust_info_id
     *
     * @return the value of mag_customer.bg_cust_info_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBgCustInfoId() {
        return bgCustInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.bg_cust_info_id
     *
     * @param bgCustInfoId the value for mag_customer.bg_cust_info_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBgCustInfoId(String bgCustInfoId) {
        this.bgCustInfoId = bgCustInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.crm_cust_info_id
     *
     * @return the value of mag_customer.crm_cust_info_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCrmCustInfoId() {
        return crmCustInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.crm_cust_info_id
     *
     * @param crmCustInfoId the value for mag_customer.crm_cust_info_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCrmCustInfoId(String crmCustInfoId) {
        this.crmCustInfoId = crmCustInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.bg_customer_id
     *
     * @return the value of mag_customer.bg_customer_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBgCustomerId() {
        return bgCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.bg_customer_id
     *
     * @param bgCustomerId the value for mag_customer.bg_customer_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBgCustomerId(String bgCustomerId) {
        this.bgCustomerId = bgCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.reference_id
     *
     * @return the value of mag_customer.reference_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.reference_id
     *
     * @param referenceId the value for mag_customer.reference_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.card_type_id
     *
     * @return the value of mag_customer.card_type_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCardTypeId() {
        return cardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.card_type_id
     *
     * @param cardTypeId the value for mag_customer.card_type_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCardTypeId(String cardTypeId) {
        this.cardTypeId = cardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.emp_number
     *
     * @return the value of mag_customer.emp_number
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getEmpNumber() {
        return empNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.emp_number
     *
     * @param empNumber the value for mag_customer.emp_number
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setEmpNumber(String empNumber) {
        this.empNumber = empNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.origin_id
     *
     * @return the value of mag_customer.origin_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getOriginId() {
        return originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.origin_id
     *
     * @param originId the value for mag_customer.origin_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setOriginId(String originId) {
        this.originId = originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.credit_pre_amount
     *
     * @return the value of mag_customer.credit_pre_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCreditPreAmount() {
        return creditPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.credit_pre_amount
     *
     * @param creditPreAmount the value for mag_customer.credit_pre_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCreditPreAmount(String creditPreAmount) {
        this.creditPreAmount = creditPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.credit_amount
     *
     * @return the value of mag_customer.credit_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.credit_amount
     *
     * @param creditAmount the value for mag_customer.credit_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCreditAmount(String creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.card_effective_time
     *
     * @return the value of mag_customer.card_effective_time
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCardEffectiveTime() {
        return cardEffectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.card_effective_time
     *
     * @param cardEffectiveTime the value for mag_customer.card_effective_time
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCardEffectiveTime(String cardEffectiveTime) {
        this.cardEffectiveTime = cardEffectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.nation
     *
     * @return the value of mag_customer.nation
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.nation
     *
     * @param nation the value for mag_customer.nation
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.birth
     *
     * @return the value of mag_customer.birth
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.birth
     *
     * @param birth the value for mag_customer.birth
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.identity_complete
     *
     * @return the value of mag_customer.identity_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getIdentityComplete() {
        return identityComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.identity_complete
     *
     * @param identityComplete the value for mag_customer.identity_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setIdentityComplete(String identityComplete) {
        this.identityComplete = identityComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.sex_name
     *
     * @return the value of mag_customer.sex_name
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getSexName() {
        return sexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.sex_name
     *
     * @param sexName the value for mag_customer.sex_name
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSexName(String sexName) {
        this.sexName = sexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.person_face_state
     *
     * @return the value of mag_customer.person_face_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPersonFaceState() {
        return personFaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.person_face_state
     *
     * @param personFaceState the value for mag_customer.person_face_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPersonFaceState(String personFaceState) {
        this.personFaceState = personFaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.Fcard_src
     *
     * @return the value of mag_customer.Fcard_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getFcardSrc() {
        return fcardSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.Fcard_src
     *
     * @param fcardSrc the value for mag_customer.Fcard_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setFcardSrc(String fcardSrc) {
        this.fcardSrc = fcardSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.Zcard_src
     *
     * @return the value of mag_customer.Zcard_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getZcardSrc() {
        return zcardSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.Zcard_src
     *
     * @param zcardSrc the value for mag_customer.Zcard_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setZcardSrc(String zcardSrc) {
        this.zcardSrc = zcardSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.author_flag
     *
     * @return the value of mag_customer.author_flag
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getAuthorFlag() {
        return authorFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.author_flag
     *
     * @param authorFlag the value for mag_customer.author_flag
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setAuthorFlag(String authorFlag) {
        this.authorFlag = authorFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.sign_address
     *
     * @return the value of mag_customer.sign_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getSignAddress() {
        return signAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.sign_address
     *
     * @param signAddress the value for mag_customer.sign_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSignAddress(String signAddress) {
        this.signAddress = signAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.is_identity
     *
     * @return the value of mag_customer.is_identity
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getIsIdentity() {
        return isIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.is_identity
     *
     * @param isIdentity the value for mag_customer.is_identity
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setIsIdentity(String isIdentity) {
        this.isIdentity = isIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.bank_error_date
     *
     * @return the value of mag_customer.bank_error_date
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBankErrorDate() {
        return bankErrorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.bank_error_date
     *
     * @param bankErrorDate the value for mag_customer.bank_error_date
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBankErrorDate(String bankErrorDate) {
        this.bankErrorDate = bankErrorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.bank_error_num
     *
     * @return the value of mag_customer.bank_error_num
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBankErrorNum() {
        return bankErrorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.bank_error_num
     *
     * @param bankErrorNum the value for mag_customer.bank_error_num
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBankErrorNum(String bankErrorNum) {
        this.bankErrorNum = bankErrorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.person_face_complete
     *
     * @return the value of mag_customer.person_face_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPersonFaceComplete() {
        return personFaceComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.person_face_complete
     *
     * @param personFaceComplete the value for mag_customer.person_face_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPersonFaceComplete(String personFaceComplete) {
        this.personFaceComplete = personFaceComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.link_man_complete
     *
     * @return the value of mag_customer.link_man_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getLinkManComplete() {
        return linkManComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.link_man_complete
     *
     * @param linkManComplete the value for mag_customer.link_man_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setLinkManComplete(String linkManComplete) {
        this.linkManComplete = linkManComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.person_info_complete
     *
     * @return the value of mag_customer.person_info_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPersonInfoComplete() {
        return personInfoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.person_info_complete
     *
     * @param personInfoComplete the value for mag_customer.person_info_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPersonInfoComplete(String personInfoComplete) {
        this.personInfoComplete = personInfoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.authorization_complete
     *
     * @return the value of mag_customer.authorization_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getAuthorizationComplete() {
        return authorizationComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.authorization_complete
     *
     * @param authorizationComplete the value for mag_customer.authorization_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setAuthorizationComplete(String authorizationComplete) {
        this.authorizationComplete = authorizationComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.three_code_num
     *
     * @return the value of mag_customer.three_code_num
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getThreeCodeNum() {
        return threeCodeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.three_code_num
     *
     * @param threeCodeNum the value for mag_customer.three_code_num
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setThreeCodeNum(String threeCodeNum) {
        this.threeCodeNum = threeCodeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.requestno
     *
     * @return the value of mag_customer.requestno
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getRequestno() {
        return requestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.requestno
     *
     * @param requestno the value for mag_customer.requestno
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setRequestno(String requestno) {
        this.requestno = requestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.sesame_state
     *
     * @return the value of mag_customer.sesame_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getSesameState() {
        return sesameState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.sesame_state
     *
     * @param sesameState the value for mag_customer.sesame_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSesameState(String sesameState) {
        this.sesameState = sesameState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.phone_host_state
     *
     * @return the value of mag_customer.phone_host_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPhoneHostState() {
        return phoneHostState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.phone_host_state
     *
     * @param phoneHostState the value for mag_customer.phone_host_state
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPhoneHostState(String phoneHostState) {
        this.phoneHostState = phoneHostState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.is_openAccount
     *
     * @return the value of mag_customer.is_openAccount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getIsOpenaccount() {
        return isOpenaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.is_openAccount
     *
     * @param isOpenaccount the value for mag_customer.is_openAccount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setIsOpenaccount(String isOpenaccount) {
        this.isOpenaccount = isOpenaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.bingcardpayno
     *
     * @return the value of mag_customer.bingcardpayno
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBingcardpayno() {
        return bingcardpayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.bingcardpayno
     *
     * @param bingcardpayno the value for mag_customer.bingcardpayno
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBingcardpayno(String bingcardpayno) {
        this.bingcardpayno = bingcardpayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.red_money
     *
     * @return the value of mag_customer.red_money
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getRedMoney() {
        return redMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.red_money
     *
     * @param redMoney the value for mag_customer.red_money
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setRedMoney(String redMoney) {
        this.redMoney = redMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.phone_task_id
     *
     * @return the value of mag_customer.phone_task_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPhoneTaskId() {
        return phoneTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.phone_task_id
     *
     * @param phoneTaskId the value for mag_customer.phone_task_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPhoneTaskId(String phoneTaskId) {
        this.phoneTaskId = phoneTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.face_src
     *
     * @return the value of mag_customer.face_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getFaceSrc() {
        return faceSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.face_src
     *
     * @param faceSrc the value for mag_customer.face_src
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setFaceSrc(String faceSrc) {
        this.faceSrc = faceSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.call_record_url
     *
     * @return the value of mag_customer.call_record_url
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getCallRecordUrl() {
        return callRecordUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.call_record_url
     *
     * @param callRecordUrl the value for mag_customer.call_record_url
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setCallRecordUrl(String callRecordUrl) {
        this.callRecordUrl = callRecordUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.invitation_id
     *
     * @return the value of mag_customer.invitation_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getInvitationId() {
        return invitationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.invitation_id
     *
     * @param invitationId the value for mag_customer.invitation_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setInvitationId(String invitationId) {
        this.invitationId = invitationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.face_state_spd
     *
     * @return the value of mag_customer.face_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getFaceStateSpd() {
        return faceStateSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.face_state_spd
     *
     * @param faceStateSpd the value for mag_customer.face_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setFaceStateSpd(String faceStateSpd) {
        this.faceStateSpd = faceStateSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.basic_complete_spd
     *
     * @return the value of mag_customer.basic_complete_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBasicCompleteSpd() {
        return basicCompleteSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.basic_complete_spd
     *
     * @param basicCompleteSpd the value for mag_customer.basic_complete_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBasicCompleteSpd(String basicCompleteSpd) {
        this.basicCompleteSpd = basicCompleteSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.phone_state_spd
     *
     * @return the value of mag_customer.phone_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPhoneStateSpd() {
        return phoneStateSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.phone_state_spd
     *
     * @param phoneStateSpd the value for mag_customer.phone_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPhoneStateSpd(String phoneStateSpd) {
        this.phoneStateSpd = phoneStateSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.authorization_complete_spd
     *
     * @return the value of mag_customer.authorization_complete_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getAuthorizationCompleteSpd() {
        return authorizationCompleteSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.authorization_complete_spd
     *
     * @param authorizationCompleteSpd the value for mag_customer.authorization_complete_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setAuthorizationCompleteSpd(String authorizationCompleteSpd) {
        this.authorizationCompleteSpd = authorizationCompleteSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.three_error_spdNum
     *
     * @return the value of mag_customer.three_error_spdNum
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getThreeErrorSpdnum() {
        return threeErrorSpdnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.three_error_spdNum
     *
     * @param threeErrorSpdnum the value for mag_customer.three_error_spdNum
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setThreeErrorSpdnum(String threeErrorSpdnum) {
        this.threeErrorSpdnum = threeErrorSpdnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.is_identity_spd
     *
     * @return the value of mag_customer.is_identity_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getIsIdentitySpd() {
        return isIdentitySpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.is_identity_spd
     *
     * @param isIdentitySpd the value for mag_customer.is_identity_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setIsIdentitySpd(String isIdentitySpd) {
        this.isIdentitySpd = isIdentitySpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.bank_errorNum_spd
     *
     * @return the value of mag_customer.bank_errorNum_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBankErrornumSpd() {
        return bankErrornumSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.bank_errorNum_spd
     *
     * @param bankErrornumSpd the value for mag_customer.bank_errorNum_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBankErrornumSpd(String bankErrornumSpd) {
        this.bankErrornumSpd = bankErrornumSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.taobao_state_spd
     *
     * @return the value of mag_customer.taobao_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getTaobaoStateSpd() {
        return taobaoStateSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.taobao_state_spd
     *
     * @param taobaoStateSpd the value for mag_customer.taobao_state_spd
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setTaobaoStateSpd(String taobaoStateSpd) {
        this.taobaoStateSpd = taobaoStateSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.marital_status
     *
     * @return the value of mag_customer.marital_status
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.marital_status
     *
     * @param maritalStatus the value for mag_customer.marital_status
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.children_status
     *
     * @return the value of mag_customer.children_status
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getChildrenStatus() {
        return childrenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.children_status
     *
     * @param childrenStatus the value for mag_customer.children_status
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setChildrenStatus(String childrenStatus) {
        this.childrenStatus = childrenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.residence_address
     *
     * @return the value of mag_customer.residence_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getResidenceAddress() {
        return residenceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.residence_address
     *
     * @param residenceAddress the value for mag_customer.residence_address
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setResidenceAddress(String residenceAddress) {
        this.residenceAddress = residenceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.Hometown_house_property
     *
     * @return the value of mag_customer.Hometown_house_property
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getHometownHouseProperty() {
        return hometownHouseProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.Hometown_house_property
     *
     * @param hometownHouseProperty the value for mag_customer.Hometown_house_property
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setHometownHouseProperty(String hometownHouseProperty) {
        this.hometownHouseProperty = hometownHouseProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.Baseinfo_complete
     *
     * @return the value of mag_customer.Baseinfo_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getBaseinfoComplete() {
        return baseinfoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.Baseinfo_complete
     *
     * @param baseinfoComplete the value for mag_customer.Baseinfo_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setBaseinfoComplete(String baseinfoComplete) {
        this.baseinfoComplete = baseinfoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.surplus_contract_amount
     *
     * @return the value of mag_customer.surplus_contract_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public BigDecimal getSurplusContractAmount() {
        return surplusContractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.surplus_contract_amount
     *
     * @param surplusContractAmount the value for mag_customer.surplus_contract_amount
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSurplusContractAmount(BigDecimal surplusContractAmount) {
        this.surplusContractAmount = surplusContractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.sync_user_id
     *
     * @return the value of mag_customer.sync_user_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public Integer getSyncUserId() {
        return syncUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.sync_user_id
     *
     * @param syncUserId the value for mag_customer.sync_user_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSyncUserId(Integer syncUserId) {
        this.syncUserId = syncUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.sync_account_id
     *
     * @return the value of mag_customer.sync_account_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public Integer getSyncAccountId() {
        return syncAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.sync_account_id
     *
     * @param syncAccountId the value for mag_customer.sync_account_id
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setSyncAccountId(Integer syncAccountId) {
        this.syncAccountId = syncAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.imageinfo_complete
     *
     * @return the value of mag_customer.imageinfo_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getImageinfoComplete() {
        return imageinfoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.imageinfo_complete
     *
     * @param imageinfoComplete the value for mag_customer.imageinfo_complete
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setImageinfoComplete(String imageinfoComplete) {
        this.imageinfoComplete = imageinfoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.Zcard_src_base64
     *
     * @return the value of mag_customer.Zcard_src_base64
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getZcardSrcBase64() {
        return zcardSrcBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.Zcard_src_base64
     *
     * @param zcardSrcBase64 the value for mag_customer.Zcard_src_base64
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setZcardSrcBase64(String zcardSrcBase64) {
        this.zcardSrcBase64 = zcardSrcBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.Fcard_src_base64
     *
     * @return the value of mag_customer.Fcard_src_base64
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getFcardSrcBase64() {
        return fcardSrcBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.Fcard_src_base64
     *
     * @param fcardSrcBase64 the value for mag_customer.Fcard_src_base64
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setFcardSrcBase64(String fcardSrcBase64) {
        this.fcardSrcBase64 = fcardSrcBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.ninetyOne_rule
     *
     * @return the value of mag_customer.ninetyOne_rule
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getNinetyoneRule() {
        return ninetyoneRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.ninetyOne_rule
     *
     * @param ninetyoneRule the value for mag_customer.ninetyOne_rule
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setNinetyoneRule(String ninetyoneRule) {
        this.ninetyoneRule = ninetyoneRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_customer.phoneBookList
     *
     * @return the value of mag_customer.phoneBookList
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public String getPhonebooklist() {
        return phonebooklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_customer.phoneBookList
     *
     * @param phonebooklist the value for mag_customer.phoneBookList
     *
     * @mbggenerated Fri Jul 20 10:08:09 CST 2018
     */
    public void setPhonebooklist(String phonebooklist) {
        this.phonebooklist = phonebooklist;
    }
}