package com.zw.miaofuspd.facade.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrderOperationRecord  implements Serializable {
    private static final long serialVersionUID = 6928169504222633712L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.operation_node
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private Integer operationNode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.operation_result
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private Integer operationResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.status
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.amount
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.order_id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.operation_time
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private String operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.emp_id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.emp_name
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_operation_record.description
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.id
     *
     * @return the value of order_operation_record.id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.id
     *
     * @param id the value for order_operation_record.id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.operation_node
     *
     * @return the value of order_operation_record.operation_node
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public Integer getOperationNode() {
        return operationNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.operation_node
     *
     * @param operationNode the value for order_operation_record.operation_node
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setOperationNode(Integer operationNode) {
        this.operationNode = operationNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.operation_result
     *
     * @return the value of order_operation_record.operation_result
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public Integer getOperationResult() {
        return operationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.operation_result
     *
     * @param operationResult the value for order_operation_record.operation_result
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setOperationResult(Integer operationResult) {
        this.operationResult = operationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.status
     *
     * @return the value of order_operation_record.status
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.status
     *
     * @param status the value for order_operation_record.status
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.amount
     *
     * @return the value of order_operation_record.amount
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.amount
     *
     * @param amount the value for order_operation_record.amount
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.order_id
     *
     * @return the value of order_operation_record.order_id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.order_id
     *
     * @param orderId the value for order_operation_record.order_id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.operation_time
     *
     * @return the value of order_operation_record.operation_time
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public String getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.operation_time
     *
     * @param operationTime the value for order_operation_record.operation_time
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setOperationTime(String operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.emp_id
     *
     * @return the value of order_operation_record.emp_id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.emp_id
     *
     * @param empId the value for order_operation_record.emp_id
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.emp_name
     *
     * @return the value of order_operation_record.emp_name
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.emp_name
     *
     * @param empName the value for order_operation_record.emp_name
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operation_record.description
     *
     * @return the value of order_operation_record.description
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operation_record.description
     *
     * @param description the value for order_operation_record.description
     *
     * @mbggenerated Fri Jul 20 10:54:13 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}