package com.zw.pojo;

public class AppMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.user_id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.title
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.content
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.creat_time
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.alter_time
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String alterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.jpush_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String jpushState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.apex1
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String apex1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.apex2
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String apex2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.apex3
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String apex3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.bak
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String bak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.push_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String pushState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.update_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String updateState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.msg_type
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.order_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.order_type
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.order_id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.id
     *
     * @return the value of app_message.id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.id
     *
     * @param id the value for app_message.id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.user_id
     *
     * @return the value of app_message.user_id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.user_id
     *
     * @param userId the value for app_message.user_id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.title
     *
     * @return the value of app_message.title
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.title
     *
     * @param title the value for app_message.title
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.content
     *
     * @return the value of app_message.content
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.content
     *
     * @param content the value for app_message.content
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.creat_time
     *
     * @return the value of app_message.creat_time
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.creat_time
     *
     * @param creatTime the value for app_message.creat_time
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.alter_time
     *
     * @return the value of app_message.alter_time
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.alter_time
     *
     * @param alterTime the value for app_message.alter_time
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setAlterTime(String alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.state
     *
     * @return the value of app_message.state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.state
     *
     * @param state the value for app_message.state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.jpush_state
     *
     * @return the value of app_message.jpush_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getJpushState() {
        return jpushState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.jpush_state
     *
     * @param jpushState the value for app_message.jpush_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setJpushState(String jpushState) {
        this.jpushState = jpushState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.apex1
     *
     * @return the value of app_message.apex1
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getApex1() {
        return apex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.apex1
     *
     * @param apex1 the value for app_message.apex1
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setApex1(String apex1) {
        this.apex1 = apex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.apex2
     *
     * @return the value of app_message.apex2
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getApex2() {
        return apex2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.apex2
     *
     * @param apex2 the value for app_message.apex2
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setApex2(String apex2) {
        this.apex2 = apex2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.apex3
     *
     * @return the value of app_message.apex3
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getApex3() {
        return apex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.apex3
     *
     * @param apex3 the value for app_message.apex3
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setApex3(String apex3) {
        this.apex3 = apex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.bak
     *
     * @return the value of app_message.bak
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getBak() {
        return bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.bak
     *
     * @param bak the value for app_message.bak
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setBak(String bak) {
        this.bak = bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.push_state
     *
     * @return the value of app_message.push_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getPushState() {
        return pushState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.push_state
     *
     * @param pushState the value for app_message.push_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setPushState(String pushState) {
        this.pushState = pushState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.update_state
     *
     * @return the value of app_message.update_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getUpdateState() {
        return updateState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.update_state
     *
     * @param updateState the value for app_message.update_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setUpdateState(String updateState) {
        this.updateState = updateState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.msg_type
     *
     * @return the value of app_message.msg_type
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.msg_type
     *
     * @param msgType the value for app_message.msg_type
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.order_state
     *
     * @return the value of app_message.order_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.order_state
     *
     * @param orderState the value for app_message.order_state
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.order_type
     *
     * @return the value of app_message.order_type
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.order_type
     *
     * @param orderType the value for app_message.order_type
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.order_id
     *
     * @return the value of app_message.order_id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.order_id
     *
     * @param orderId the value for app_message.order_id
     *
     * @mbggenerated Sat Jul 21 13:20:37 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
}