package com.zw.pojo;


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * @author cqy
 */
public class Order implements Serializable {
    private static final long serialVersionUID = -5565783333997378967L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.order_no
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.USER_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.MERCHANT_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.MERCHANT_NAME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.CUSTOMER_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.CUSTOMER_NAME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.sex_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String sexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.TEL
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.CARD_TYPE
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.CARD
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.CREDIT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.PRECREDIT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String precredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.AMOUNT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.COMPANY
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.BRANCH
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.emp_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.MANAGER
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.MANAGER
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String isRepayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.PERIODS
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String periods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.CREAT_TIME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.applay_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String applayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.ALTER_TIME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String alterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.loan_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String loanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.repay_date
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String repayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.APEX3
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String apex3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.BAK
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String bak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.repay_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.rate
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_brand
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_model
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_brand_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseBrandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_code
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_version_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_type_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.provinces_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String provincesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.city_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.distric_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String districId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.provinces
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String provinces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.city
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.distric
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String distric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_kind
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_type_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_Id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_name_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productNameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_detail
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_detail_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productDetailName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.product_detail_code
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String productDetailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.sex
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.emp_number
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String empNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.applay_money
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private BigDecimal applayMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.loan_amount
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.contract_amount
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private BigDecimal contractAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.repay_money
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String repayMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.order_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.predict_price
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String predictPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.receive_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String receiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.is_refuse
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String isRefuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.commodity_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String commodityState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.withdraw_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String withdrawState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.order_submission_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String orderSubmissionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.source
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.contract_no
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.overdue_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String overdueState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.manageFee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String managefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.quickTrialFee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String quicktrialfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.fee_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String feeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_version
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.requestno
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String requestno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.is_sign
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String isSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.weight
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.price
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.identry_rule_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String identryRuleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.person_rule_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String personRuleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.yuqi_fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String yuqiFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.delivery_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String deliveryState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.rebates_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String rebatesState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.goldMass
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String goldmass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.answer_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String answerState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.answer_score
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String answerScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.loan_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String loanState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.contract_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String contractTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.diy_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String diyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.diy_days
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String diyDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.offline_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String offlineOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.Job
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.Examine_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String examineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.Service_fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String serviceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.Order_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.loan_purpose
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String loanPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.complete
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String complete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.asset_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String assetState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.pay_back_user
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String payBackUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.pay_back_card
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String payBackCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.bankId
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String bankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.merchandise_url
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String merchandiseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mag_order.score_card
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    private String scoreCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.ID
     *
     * @return the value of mag_order.ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.ID
     *
     * @param id the value for mag_order.ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.order_no
     *
     * @return the value of mag_order.order_no
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.order_no
     *
     * @param orderNo the value for mag_order.order_no
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.USER_ID
     *
     * @return the value of mag_order.USER_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.USER_ID
     *
     * @param userId the value for mag_order.USER_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.MERCHANT_ID
     *
     * @return the value of mag_order.MERCHANT_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.MERCHANT_ID
     *
     * @param merchantId the value for mag_order.MERCHANT_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.MERCHANT_NAME
     *
     * @return the value of mag_order.MERCHANT_NAME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.MERCHANT_NAME
     *
     * @param merchantName the value for mag_order.MERCHANT_NAME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.CUSTOMER_ID
     *
     * @return the value of mag_order.CUSTOMER_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.CUSTOMER_ID
     *
     * @param customerId the value for mag_order.CUSTOMER_ID
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.CUSTOMER_NAME
     *
     * @return the value of mag_order.CUSTOMER_NAME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.CUSTOMER_NAME
     *
     * @param customerName the value for mag_order.CUSTOMER_NAME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.sex_name
     *
     * @return the value of mag_order.sex_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getSexName() {
        return sexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.sex_name
     *
     * @param sexName the value for mag_order.sex_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setSexName(String sexName) {
        this.sexName = sexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.TEL
     *
     * @return the value of mag_order.TEL
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.TEL
     *
     * @param tel the value for mag_order.TEL
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.CARD_TYPE
     *
     * @return the value of mag_order.CARD_TYPE
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.CARD_TYPE
     *
     * @param cardType the value for mag_order.CARD_TYPE
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.CARD
     *
     * @return the value of mag_order.CARD
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.CARD
     *
     * @param card the value for mag_order.CARD
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.CREDIT
     *
     * @return the value of mag_order.CREDIT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.CREDIT
     *
     * @param credit the value for mag_order.CREDIT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCredit(String credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.PRECREDIT
     *
     * @return the value of mag_order.PRECREDIT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getPrecredit() {
        return precredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.PRECREDIT
     *
     * @param precredit the value for mag_order.PRECREDIT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPrecredit(String precredit) {
        this.precredit = precredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.AMOUNT
     *
     * @return the value of mag_order.AMOUNT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.AMOUNT
     *
     * @param amount the value for mag_order.AMOUNT
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.COMPANY
     *
     * @return the value of mag_order.COMPANY
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.COMPANY
     *
     * @param company the value for mag_order.COMPANY
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.BRANCH
     *
     * @return the value of mag_order.BRANCH
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.BRANCH
     *
     * @param branch the value for mag_order.BRANCH
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.emp_id
     *
     * @return the value of mag_order.emp_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.emp_id
     *
     * @param empId the value for mag_order.emp_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.MANAGER
     *
     * @return the value of mag_order.MANAGER
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.MANAGER
     *
     * @param manager the value for mag_order.MANAGER
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.PERIODS
     *
     * @return the value of mag_order.PERIODS
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getPeriods() {
        return periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.PERIODS
     *
     * @param periods the value for mag_order.PERIODS
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPeriods(String periods) {
        this.periods = periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.CREAT_TIME
     *
     * @return the value of mag_order.CREAT_TIME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.CREAT_TIME
     *
     * @param creatTime the value for mag_order.CREAT_TIME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.applay_time
     *
     * @return the value of mag_order.applay_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getApplayTime() {
        return applayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.applay_time
     *
     * @param applayTime the value for mag_order.applay_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setApplayTime(String applayTime) {
        this.applayTime = applayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.ALTER_TIME
     *
     * @return the value of mag_order.ALTER_TIME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.ALTER_TIME
     *
     * @param alterTime the value for mag_order.ALTER_TIME
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setAlterTime(String alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.loan_time
     *
     * @return the value of mag_order.loan_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.loan_time
     *
     * @param loanTime the value for mag_order.loan_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setLoanTime(String loanTime) {
        this.loanTime = loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.repay_date
     *
     * @return the value of mag_order.repay_date
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getRepayDate() {
        return repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.repay_date
     *
     * @param repayDate the value for mag_order.repay_date
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setRepayDate(String repayDate) {
        this.repayDate = repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.fee
     *
     * @return the value of mag_order.fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.fee
     *
     * @param fee the value for mag_order.fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setFee(String fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.APEX3
     *
     * @return the value of mag_order.APEX3
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getApex3() {
        return apex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.APEX3
     *
     * @param apex3 the value for mag_order.APEX3
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setApex3(String apex3) {
        this.apex3 = apex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.BAK
     *
     * @return the value of mag_order.BAK
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getBak() {
        return bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.BAK
     *
     * @param bak the value for mag_order.BAK
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setBak(String bak) {
        this.bak = bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.state
     *
     * @return the value of mag_order.state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.state
     *
     * @param state the value for mag_order.state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.repay_type
     *
     * @return the value of mag_order.repay_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.repay_type
     *
     * @param repayType the value for mag_order.repay_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setRepayType(String repayType) {
        this.repayType = repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.rate
     *
     * @return the value of mag_order.rate
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.rate
     *
     * @param rate the value for mag_order.rate
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_type
     *
     * @return the value of mag_order.merchandise_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseType() {
        return merchandiseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_type
     *
     * @param merchandiseType the value for mag_order.merchandise_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseType(String merchandiseType) {
        this.merchandiseType = merchandiseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_name
     *
     * @return the value of mag_order.merchandise_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseName() {
        return merchandiseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_name
     *
     * @param merchandiseName the value for mag_order.merchandise_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseName(String merchandiseName) {
        this.merchandiseName = merchandiseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_id
     *
     * @return the value of mag_order.merchandise_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_id
     *
     * @param merchandiseId the value for mag_order.merchandise_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseId(String merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_brand
     *
     * @return the value of mag_order.merchandise_brand
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseBrand() {
        return merchandiseBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_brand
     *
     * @param merchandiseBrand the value for mag_order.merchandise_brand
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseBrand(String merchandiseBrand) {
        this.merchandiseBrand = merchandiseBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_model
     *
     * @return the value of mag_order.merchandise_model
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseModel() {
        return merchandiseModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_model
     *
     * @param merchandiseModel the value for mag_order.merchandise_model
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseModel(String merchandiseModel) {
        this.merchandiseModel = merchandiseModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_brand_id
     *
     * @return the value of mag_order.merchandise_brand_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseBrandId() {
        return merchandiseBrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_brand_id
     *
     * @param merchandiseBrandId the value for mag_order.merchandise_brand_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseBrandId(String merchandiseBrandId) {
        this.merchandiseBrandId = merchandiseBrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_code
     *
     * @return the value of mag_order.merchandise_code
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseCode() {
        return merchandiseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_code
     *
     * @param merchandiseCode the value for mag_order.merchandise_code
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseCode(String merchandiseCode) {
        this.merchandiseCode = merchandiseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_version_id
     *
     * @return the value of mag_order.merchandise_version_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseVersionId() {
        return merchandiseVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_version_id
     *
     * @param merchandiseVersionId the value for mag_order.merchandise_version_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseVersionId(String merchandiseVersionId) {
        this.merchandiseVersionId = merchandiseVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_type_id
     *
     * @return the value of mag_order.merchandise_type_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseTypeId() {
        return merchandiseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_type_id
     *
     * @param merchandiseTypeId the value for mag_order.merchandise_type_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseTypeId(String merchandiseTypeId) {
        this.merchandiseTypeId = merchandiseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.provinces_id
     *
     * @return the value of mag_order.provinces_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProvincesId() {
        return provincesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.provinces_id
     *
     * @param provincesId the value for mag_order.provinces_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProvincesId(String provincesId) {
        this.provincesId = provincesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.city_id
     *
     * @return the value of mag_order.city_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.city_id
     *
     * @param cityId the value for mag_order.city_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.distric_id
     *
     * @return the value of mag_order.distric_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getDistricId() {
        return districId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.distric_id
     *
     * @param districId the value for mag_order.distric_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setDistricId(String districId) {
        this.districId = districId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.provinces
     *
     * @return the value of mag_order.provinces
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProvinces() {
        return provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.provinces
     *
     * @param provinces the value for mag_order.provinces
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProvinces(String provinces) {
        this.provinces = provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.city
     *
     * @return the value of mag_order.city
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.city
     *
     * @param city the value for mag_order.city
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.distric
     *
     * @return the value of mag_order.distric
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getDistric() {
        return distric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.distric
     *
     * @param distric the value for mag_order.distric
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setDistric(String distric) {
        this.distric = distric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_kind
     *
     * @return the value of mag_order.product_kind
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductKind() {
        return productKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_kind
     *
     * @param productKind the value for mag_order.product_kind
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductKind(String productKind) {
        this.productKind = productKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_type
     *
     * @return the value of mag_order.product_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_type
     *
     * @param productType the value for mag_order.product_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_type_name
     *
     * @return the value of mag_order.product_type_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_type_name
     *
     * @param productTypeName the value for mag_order.product_type_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_Id
     *
     * @return the value of mag_order.product_Id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_Id
     *
     * @param productId the value for mag_order.product_Id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_name
     *
     * @return the value of mag_order.product_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_name
     *
     * @param productName the value for mag_order.product_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_name_name
     *
     * @return the value of mag_order.product_name_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductNameName() {
        return productNameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_name_name
     *
     * @param productNameName the value for mag_order.product_name_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductNameName(String productNameName) {
        this.productNameName = productNameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_detail
     *
     * @return the value of mag_order.product_detail
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductDetail() {
        return productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_detail
     *
     * @param productDetail the value for mag_order.product_detail
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_detail_name
     *
     * @return the value of mag_order.product_detail_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductDetailName() {
        return productDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_detail_name
     *
     * @param productDetailName the value for mag_order.product_detail_name
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductDetailName(String productDetailName) {
        this.productDetailName = productDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.product_detail_code
     *
     * @return the value of mag_order.product_detail_code
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getProductDetailCode() {
        return productDetailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.product_detail_code
     *
     * @param productDetailCode the value for mag_order.product_detail_code
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setProductDetailCode(String productDetailCode) {
        this.productDetailCode = productDetailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.sex
     *
     * @return the value of mag_order.sex
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.sex
     *
     * @param sex the value for mag_order.sex
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.emp_number
     *
     * @return the value of mag_order.emp_number
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getEmpNumber() {
        return empNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.emp_number
     *
     * @param empNumber the value for mag_order.emp_number
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setEmpNumber(String empNumber) {
        this.empNumber = empNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.applay_money
     *
     * @return the value of mag_order.applay_money
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public BigDecimal getApplayMoney() {
        return applayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.applay_money
     *
     * @param applayMoney the value for mag_order.applay_money
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setApplayMoney(BigDecimal applayMoney) {
        this.applayMoney = applayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.loan_amount
     *
     * @return the value of mag_order.loan_amount
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.loan_amount
     *
     * @param loanAmount the value for mag_order.loan_amount
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setLoanAmount(String loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.contract_amount
     *
     * @return the value of mag_order.contract_amount
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public BigDecimal getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.contract_amount
     *
     * @param contractAmount the value for mag_order.contract_amount
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setContractAmount(BigDecimal contractAmount) {
        this.contractAmount = contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.repay_money
     *
     * @return the value of mag_order.repay_money
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getRepayMoney() {
        return repayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.repay_money
     *
     * @param repayMoney the value for mag_order.repay_money
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setRepayMoney(String repayMoney) {
        this.repayMoney = repayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.order_type
     *
     * @return the value of mag_order.order_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.order_type
     *
     * @param orderType the value for mag_order.order_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.predict_price
     *
     * @return the value of mag_order.predict_price
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getPredictPrice() {
        return predictPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.predict_price
     *
     * @param predictPrice the value for mag_order.predict_price
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPredictPrice(String predictPrice) {
        this.predictPrice = predictPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.receive_id
     *
     * @return the value of mag_order.receive_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.receive_id
     *
     * @param receiveId the value for mag_order.receive_id
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setReceiveId(String receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.is_refuse
     *
     * @return the value of mag_order.is_refuse
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getIsRefuse() {
        return isRefuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.is_refuse
     *
     * @param isRefuse the value for mag_order.is_refuse
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setIsRefuse(String isRefuse) {
        this.isRefuse = isRefuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.commodity_state
     *
     * @return the value of mag_order.commodity_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getCommodityState() {
        return commodityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.commodity_state
     *
     * @param commodityState the value for mag_order.commodity_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setCommodityState(String commodityState) {
        this.commodityState = commodityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.withdraw_state
     *
     * @return the value of mag_order.withdraw_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getWithdrawState() {
        return withdrawState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.withdraw_state
     *
     * @param withdrawState the value for mag_order.withdraw_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setWithdrawState(String withdrawState) {
        this.withdrawState = withdrawState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.order_submission_time
     *
     * @return the value of mag_order.order_submission_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getOrderSubmissionTime() {
        return orderSubmissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.order_submission_time
     *
     * @param orderSubmissionTime the value for mag_order.order_submission_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setOrderSubmissionTime(String orderSubmissionTime) {
        this.orderSubmissionTime = orderSubmissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.source
     *
     * @return the value of mag_order.source
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.source
     *
     * @param source the value for mag_order.source
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.contract_no
     *
     * @return the value of mag_order.contract_no
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.contract_no
     *
     * @param contractNo the value for mag_order.contract_no
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.overdue_state
     *
     * @return the value of mag_order.overdue_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getOverdueState() {
        return overdueState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.overdue_state
     *
     * @param overdueState the value for mag_order.overdue_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setOverdueState(String overdueState) {
        this.overdueState = overdueState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.manageFee
     *
     * @return the value of mag_order.manageFee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getManagefee() {
        return managefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.manageFee
     *
     * @param managefee the value for mag_order.manageFee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setManagefee(String managefee) {
        this.managefee = managefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.quickTrialFee
     *
     * @return the value of mag_order.quickTrialFee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getQuicktrialfee() {
        return quicktrialfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.quickTrialFee
     *
     * @param quicktrialfee the value for mag_order.quickTrialFee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setQuicktrialfee(String quicktrialfee) {
        this.quicktrialfee = quicktrialfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.fee_state
     *
     * @return the value of mag_order.fee_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getFeeState() {
        return feeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.fee_state
     *
     * @param feeState the value for mag_order.fee_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setFeeState(String feeState) {
        this.feeState = feeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_version
     *
     * @return the value of mag_order.merchandise_version
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseVersion() {
        return merchandiseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_version
     *
     * @param merchandiseVersion the value for mag_order.merchandise_version
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseVersion(String merchandiseVersion) {
        this.merchandiseVersion = merchandiseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.requestno
     *
     * @return the value of mag_order.requestno
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getRequestno() {
        return requestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.requestno
     *
     * @param requestno the value for mag_order.requestno
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setRequestno(String requestno) {
        this.requestno = requestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.is_sign
     *
     * @return the value of mag_order.is_sign
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.is_sign
     *
     * @param isSign the value for mag_order.is_sign
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setIsSign(String isSign) {
        this.isSign = isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.weight
     *
     * @return the value of mag_order.weight
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.weight
     *
     * @param weight the value for mag_order.weight
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.price
     *
     * @return the value of mag_order.price
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.price
     *
     * @param price the value for mag_order.price
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.identry_rule_state
     *
     * @return the value of mag_order.identry_rule_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getIdentryRuleState() {
        return identryRuleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.identry_rule_state
     *
     * @param identryRuleState the value for mag_order.identry_rule_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setIdentryRuleState(String identryRuleState) {
        this.identryRuleState = identryRuleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.person_rule_state
     *
     * @return the value of mag_order.person_rule_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getPersonRuleState() {
        return personRuleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.person_rule_state
     *
     * @param personRuleState the value for mag_order.person_rule_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPersonRuleState(String personRuleState) {
        this.personRuleState = personRuleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.yuqi_fee
     *
     * @return the value of mag_order.yuqi_fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getYuqiFee() {
        return yuqiFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.yuqi_fee
     *
     * @param yuqiFee the value for mag_order.yuqi_fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setYuqiFee(String yuqiFee) {
        this.yuqiFee = yuqiFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.delivery_state
     *
     * @return the value of mag_order.delivery_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getDeliveryState() {
        return deliveryState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.delivery_state
     *
     * @param deliveryState the value for mag_order.delivery_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setDeliveryState(String deliveryState) {
        this.deliveryState = deliveryState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.rebates_state
     *
     * @return the value of mag_order.rebates_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getRebatesState() {
        return rebatesState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.rebates_state
     *
     * @param rebatesState the value for mag_order.rebates_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setRebatesState(String rebatesState) {
        this.rebatesState = rebatesState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.goldMass
     *
     * @return the value of mag_order.goldMass
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getGoldmass() {
        return goldmass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.goldMass
     *
     * @param goldmass the value for mag_order.goldMass
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setGoldmass(String goldmass) {
        this.goldmass = goldmass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.answer_state
     *
     * @return the value of mag_order.answer_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getAnswerState() {
        return answerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.answer_state
     *
     * @param answerState the value for mag_order.answer_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setAnswerState(String answerState) {
        this.answerState = answerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.answer_score
     *
     * @return the value of mag_order.answer_score
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getAnswerScore() {
        return answerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.answer_score
     *
     * @param answerScore the value for mag_order.answer_score
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setAnswerScore(String answerScore) {
        this.answerScore = answerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.loan_state
     *
     * @return the value of mag_order.loan_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getLoanState() {
        return loanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.loan_state
     *
     * @param loanState the value for mag_order.loan_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setLoanState(String loanState) {
        this.loanState = loanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.contract_time
     *
     * @return the value of mag_order.contract_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getContractTime() {
        return contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.contract_time
     *
     * @param contractTime the value for mag_order.contract_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setContractTime(String contractTime) {
        this.contractTime = contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.diy_type
     *
     * @return the value of mag_order.diy_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getDiyType() {
        return diyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.diy_type
     *
     * @param diyType the value for mag_order.diy_type
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setDiyType(String diyType) {
        this.diyType = diyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.diy_days
     *
     * @return the value of mag_order.diy_days
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getDiyDays() {
        return diyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.diy_days
     *
     * @param diyDays the value for mag_order.diy_days
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setDiyDays(String diyDays) {
        this.diyDays = diyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.offline_order
     *
     * @return the value of mag_order.offline_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getOfflineOrder() {
        return offlineOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.offline_order
     *
     * @param offlineOrder the value for mag_order.offline_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setOfflineOrder(String offlineOrder) {
        this.offlineOrder = offlineOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.Job
     *
     * @return the value of mag_order.Job
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.Job
     *
     * @param job the value for mag_order.Job
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.Examine_time
     *
     * @return the value of mag_order.Examine_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getExamineTime() {
        return examineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.Examine_time
     *
     * @param examineTime the value for mag_order.Examine_time
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setExamineTime(String examineTime) {
        this.examineTime = examineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.Service_fee
     *
     * @return the value of mag_order.Service_fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getServiceFee() {
        return serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.Service_fee
     *
     * @param serviceFee the value for mag_order.Service_fee
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setServiceFee(String serviceFee) {
        this.serviceFee = serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.Order_state
     *
     * @return the value of mag_order.Order_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.Order_state
     *
     * @param orderState the value for mag_order.Order_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.loan_purpose
     *
     * @return the value of mag_order.loan_purpose
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getLoanPurpose() {
        return loanPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.loan_purpose
     *
     * @param loanPurpose the value for mag_order.loan_purpose
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setLoanPurpose(String loanPurpose) {
        this.loanPurpose = loanPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.complete
     *
     * @return the value of mag_order.complete
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.complete
     *
     * @param complete the value for mag_order.complete
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setComplete(String complete) {
        this.complete = complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.asset_state
     *
     * @return the value of mag_order.asset_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getAssetState() {
        return assetState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.asset_state
     *
     * @param assetState the value for mag_order.asset_state
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setAssetState(String assetState) {
        this.assetState = assetState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.pay_back_user
     *
     * @return the value of mag_order.pay_back_user
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getPayBackUser() {
        return payBackUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.pay_back_user
     *
     * @param payBackUser the value for mag_order.pay_back_user
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPayBackUser(String payBackUser) {
        this.payBackUser = payBackUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.pay_back_card
     *
     * @return the value of mag_order.pay_back_card
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getPayBackCard() {
        return payBackCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.pay_back_card
     *
     * @param payBackCard the value for mag_order.pay_back_card
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setPayBackCard(String payBackCard) {
        this.payBackCard = payBackCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.bankId
     *
     * @return the value of mag_order.bankId
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.bankId
     *
     * @param bankid the value for mag_order.bankId
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setBankid(String bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.merchandise_url
     *
     * @return the value of mag_order.merchandise_url
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getMerchandiseUrl() {
        return merchandiseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.merchandise_url
     *
     * @param merchandiseUrl the value for mag_order.merchandise_url
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setMerchandiseUrl(String merchandiseUrl) {
        this.merchandiseUrl = merchandiseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mag_order.score_card
     *
     * @return the value of mag_order.score_card
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public String getScoreCard() {
        return scoreCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mag_order.score_card
     *
     * @param scoreCard the value for mag_order.score_card
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    public void setScoreCard(String scoreCard) {
        this.scoreCard = scoreCard;
    }

    public String getIsRepayment() {
        return isRepayment;
    }

    public void setIsRepayment(String isRepayment) {
        this.isRepayment = isRepayment;
    }
}