package com.zw.miaofuspd.mapper;


import com.zw.miaofuspd.facade.pojo.MagOrder;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MagOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    int insert(MagOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    MagOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    List<MagOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mag_order
     *
     * @mbggenerated Thu Jul 19 14:59:41 CST 2018
     */
    int updateByPrimaryKey(MagOrder record);


    /**
     * 按id更新订单信息
     * @author 陈淸玉 create on 2018-07-19
     * @param order 订单实体
     * @return 影响行数
     */
    int updateOrderById(MagOrder order);

    /**
     * 按id获取订单信息
     * @author 陈淸玉 create on 2018-07-19
     * @param orderId 订单Id
     * @return 一条订单数据
     */
    MagOrder getOrderInfoById(@Param("orderId") String orderId);
}